"""initial schema

Revision ID: 20260425_0001
Revises: 
Create Date: 2026-04-25 21:42:36.810621
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20260425_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=False),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_clerk_user_id'), 'app_user', ['clerk_user_id'], unique=True)
    op.create_table('app_chat_attachment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_chat_attachment_user_id'), 'app_chat_attachment', ['user_id'], unique=False)
    op.create_table('app_chat_thread',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status_json', sa.JSON(), nullable=False),
    sa.Column('allowed_image_domains_json', sa.JSON(), nullable=True),
    sa.Column('updated_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_chat_thread_user_id'), 'app_chat_thread', ['user_id'], unique=False)
    op.create_index('ix_app_chat_thread_user_updated_sequence', 'app_chat_thread', ['user_id', 'updated_sequence'], unique=False)
    op.create_table('user_library',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('openai_vector_store_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_library_user_id')
    )
    op.create_index(op.f('ix_user_library_openai_vector_store_id'), 'user_library', ['openai_vector_store_id'], unique=True)
    op.create_index(op.f('ix_user_library_user_id'), 'user_library', ['user_id'], unique=False)
    op.create_index('ix_user_library_user_updated_at', 'user_library', ['user_id', 'updated_at'], unique=False)
    op.create_table('app_chat_entry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['app_chat_thread.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'sequence', name='uq_app_chat_entry_thread_sequence')
    )
    op.create_index(op.f('ix_app_chat_entry_thread_id'), 'app_chat_entry', ['thread_id'], unique=False)
    op.create_index('ix_app_chat_entry_thread_sequence', 'app_chat_entry', ['thread_id', 'sequence'], unique=False)
    op.create_table('source_file',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('display_title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=48), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('openai_original_file_id', sa.String(length=128), nullable=True),
    sa.Column('ingest_strategy', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['user_library.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'display_title', name='uq_source_file_display_title'),
    sa.UniqueConstraint('openai_original_file_id')
    )
    op.create_index(op.f('ix_source_file_library_id'), 'source_file', ['library_id'], unique=False)
    op.create_index('ix_source_file_library_status_created_at', 'source_file', ['library_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_source_file_uploaded_by_user_id'), 'source_file', ['uploaded_by_user_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['user_library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'name', name='uq_tag_library_name'),
    sa.UniqueConstraint('library_id', 'slug', name='uq_tag_library_slug')
    )
    op.create_index(op.f('ix_tag_library_id'), 'tag', ['library_id'], unique=False)
    op.create_table('app_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('origin_surface', sa.String(length=32), nullable=False),
    sa.Column('origin_thread_id', sa.String(length=64), nullable=True),
    sa.Column('source_file_id', sa.String(length=32), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['user_library.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_task_library_created_at', 'app_task', ['library_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_app_task_library_id'), 'app_task', ['library_id'], unique=False)
    op.create_index(op.f('ix_app_task_origin_thread_id'), 'app_task', ['origin_thread_id'], unique=False)
    op.create_index(op.f('ix_app_task_source_file_id'), 'app_task', ['source_file_id'], unique=False)
    op.create_index('ix_app_task_status_created_at', 'app_task', ['status', 'created_at'], unique=False)
    op.create_index('ix_app_task_user_created_at', 'app_task', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_app_task_user_id'), 'app_task', ['user_id'], unique=False)
    op.create_table('semantic_chunk',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_file_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('locator_type', sa.String(length=32), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('start_seconds', sa.Float(), nullable=True),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('strategy_label', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('openai_file_id', sa.String(length=128), nullable=True),
    sa.Column('vector_attributes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openai_file_id'),
    sa.UniqueConstraint('source_file_id', 'sequence', name='uq_semantic_chunk_source_sequence')
    )
    op.create_index('ix_semantic_chunk_openai_file_id', 'semantic_chunk', ['openai_file_id'], unique=False)
    op.create_index(op.f('ix_semantic_chunk_source_file_id'), 'semantic_chunk', ['source_file_id'], unique=False)
    op.create_index('ix_semantic_chunk_source_status_sequence', 'semantic_chunk', ['source_file_id', 'status', 'sequence'], unique=False)
    op.create_table('source_tag_link',
    sa.Column('source_file_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_file.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('source_file_id', 'tag_id')
    )
    op.create_table('stored_asset',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=48), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['user_library.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['app_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_asset_library_id'), 'stored_asset', ['library_id'], unique=False)
    op.create_index('ix_stored_asset_library_kind_created_at', 'stored_asset', ['library_id', 'kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_stored_asset_task_id'), 'stored_asset', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_asset_task_id'), table_name='stored_asset')
    op.drop_index('ix_stored_asset_library_kind_created_at', table_name='stored_asset')
    op.drop_index(op.f('ix_stored_asset_library_id'), table_name='stored_asset')
    op.drop_table('stored_asset')
    op.drop_table('source_tag_link')
    op.drop_index('ix_semantic_chunk_source_status_sequence', table_name='semantic_chunk')
    op.drop_index(op.f('ix_semantic_chunk_source_file_id'), table_name='semantic_chunk')
    op.drop_index('ix_semantic_chunk_openai_file_id', table_name='semantic_chunk')
    op.drop_table('semantic_chunk')
    op.drop_index(op.f('ix_app_task_user_id'), table_name='app_task')
    op.drop_index('ix_app_task_user_created_at', table_name='app_task')
    op.drop_index('ix_app_task_status_created_at', table_name='app_task')
    op.drop_index(op.f('ix_app_task_source_file_id'), table_name='app_task')
    op.drop_index(op.f('ix_app_task_origin_thread_id'), table_name='app_task')
    op.drop_index(op.f('ix_app_task_library_id'), table_name='app_task')
    op.drop_index('ix_app_task_library_created_at', table_name='app_task')
    op.drop_table('app_task')
    op.drop_index(op.f('ix_tag_library_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_source_file_uploaded_by_user_id'), table_name='source_file')
    op.drop_index('ix_source_file_library_status_created_at', table_name='source_file')
    op.drop_index(op.f('ix_source_file_library_id'), table_name='source_file')
    op.drop_table('source_file')
    op.drop_index('ix_app_chat_entry_thread_sequence', table_name='app_chat_entry')
    op.drop_index(op.f('ix_app_chat_entry_thread_id'), table_name='app_chat_entry')
    op.drop_table('app_chat_entry')
    op.drop_index('ix_user_library_user_updated_at', table_name='user_library')
    op.drop_index(op.f('ix_user_library_user_id'), table_name='user_library')
    op.drop_index(op.f('ix_user_library_openai_vector_store_id'), table_name='user_library')
    op.drop_table('user_library')
    op.drop_index('ix_app_chat_thread_user_updated_sequence', table_name='app_chat_thread')
    op.drop_index(op.f('ix_app_chat_thread_user_id'), table_name='app_chat_thread')
    op.drop_table('app_chat_thread')
    op.drop_index(op.f('ix_app_chat_attachment_user_id'), table_name='app_chat_attachment')
    op.drop_table('app_chat_attachment')
    op.drop_index(op.f('ix_app_user_clerk_user_id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
